# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenstorage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstore',
            name='vsts_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenstore',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenstore',
            name='slack_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
