# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenstorage', '0004_auto_20170309_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenstore',
            name='instance_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tokenstore',
            name='user_email',
            field=models.EmailField(default='invalid@email.com', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='tokenstore',
            unique_together=set([('instance_id', 'user_email')]),
        ),
    ]
