# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenstorage', '0005_auto_20170309_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenstore',
            name='github_org',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tokenstore',
            name='github_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
